<?php
/**
 * Drupal Plugin - Module
 *
 * PHP version 5.3
 *
 * @category Plugins
 * @package  Drupal
 * @author   Oytun Tez <oytun@motaword.com>
 */

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_mw_tmgmt_translator_plugin_info() {
  return array(
    'mw' => array(
      'label' => t('MotaWord translator'),
      'description' => t('A MotaWord translator service.'),
      'plugin controller class' => 'TMGMTMWPluginController',
      'ui controller class' => 'TMGMTMWTranslatorUIController',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function tmgmt_mw_menu() {
  return array(
    'tmgmt_mw_callback' => array(
      'title' => 'mw_callback',
      'description' => '',
      'page callback' => 'tmgmt_mw_callback',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Callback for MW requests.
 */
function tmgmt_mw_callback() {
  if (!isset($_POST['type']) || !$_POST['type'] || !isset($_POST['action']) || !$_POST['action'] || !isset($_POST['project']) || !$_POST['project']) {
    watchdog(
      'tmgmt',
      'Wrong query for updating job status',
      array(),
      WATCHDOG_CRITICAL
    );

    echo 'Missing parameters.';

    drupal_exit();
  }

  $type = $_POST['type'];
  $action = $_POST['action'];
  $project = (object) $_POST['project'];

  if (!property_exists($project, 'custom')) {
    watchdog(
      'tmgmt',
      'Wrong query for updating job status',
      array(),
      WATCHDOG_CRITICAL
    );

    echo 'Missing Drupal parameters.';

    drupal_exit();
  }

  $custom = (object) $project->custom;

  $job = tmgmt_job_load($custom->job_id);
  if (empty($job)) {
    watchdog(
      'tmgmt',
      'Could not find job #%job_id',
      array('%job_id' => $custom->job_id),
      WATCHDOG_CRITICAL
    );

    echo 'Missing job.';

    drupal_exit();
  }
  /**
   * @var TMGMTMWPluginController $mw The translator object.
   */
  $mw = $job->getTranslator()->getController();

  switch ($type) {
    case 'project':
      if ($action === 'translated') {
        echo 'translated';

        $job->addMessage(
          'Your project has been translated. Waiting to be proofread.'
        );

        drupal_exit();
      }
      elseif ($action === 'proofread') {
        echo 'proofread';

        $job->addMessage('Your project\'s proofreading is now complete.');

        $mw->retrieveTranslation($job);

        drupal_exit();
      }

      break;

    default:
      watchdog(
        'tmgmt',
        'Callback actions did not match. Quitting.',
        array(),
        WATCHDOG_CRITICAL
      );

      echo 'Action missing.';

      drupal_exit();
  }
}